### PR TITLE
Added a if in case the link aint from insta nor yt

### PR DESCRIPTION
**Pull request by Vexxenn**
@elubow Added validation in case the link ain't from youtube nor instagram. This was necessary since links from bjjglobetrotters always showed up not working.

### CODE REVIEW

**Comment by elubow** [comment]
@Vexxenn The links from BJJ Globetrotters are ultimately YT videos. Do you think there is a way that we could figure out the YT link on that page and create an embed out of that? Perhaps with the thing that downloads the images? I can always create another ticket out of that task if you think it's possible.

**Comment by Vexxenn** [comment]
@elubow Yea i also noticed the videos they had were YT videos. I will look a bit into it and see if it's possible to fetch them.

**Comment by Vexxenn** [comment]
@elubow So after searching for a while i think it isn't possible to get the YT link. Went to check `GetVideoMetadataJob` to see if there was anything related to the video and there was nothing (the array that usually contains the video link was empty). Also tried to get the info with some jQuery but it isn't possible to access the information inside an iframe.

**Comment by elubow** [comment]
@Vexxenn Great. Thanks for trying though.

**Pull request merged**
