### PR TITLE
Added admin video list

### PR DESCRIPTION
**Pull request by Vexxenn**
@elubow So i have added a new option to the admin navbar partial and it will redirect to a view containing all videos without showing the instructors. Also changed the partial view _list to display the instructors column based on a condition (thought this would be better then creating and entier new partial view to only use for this admin view)

### CODE REVIEW

**Comment by elubow** [comment]
@Vexxenn Perhaps I should have been more clear here. This one is my fault. I meant that I wanted to see a list of videos that have zero instructors. Not a list of videos without the instructor column.

**Comment by Vexxenn** [comment]
@elubow Ho then yea i will do the required changes but i am going to try to take care of the other issue first.

**Comment by Vexxenn** [comment]
@elubow Well maybe i will pick this up (and the other issue) after i finish the stars ratting that i had started yesterday. Shouldn't take too long so i will still look in to this and the issue today, plus maybe i will come across the issue while i take care of these two.

**Comment by elubow** [comment]
Ok. The main thing I'd like to make sure is that I can add videos without it erroring. So whatever else you get to is fine. But I think I want to make sure that the site doesn't 500.

**Comment by elubow** [comment]
It wasn't doing that before and we didn't change anything there. But I'll try it tonight and let you know.

**Comment by elubow** [comment]
@Vexxenn Yup, that change worked to fix the issue. I can now add videos again. Thank you.

**Pull request merged**
